# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: build
  displayName: Build and Run Integrartion tests
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
          docker volume create --driver local --opt type=none --opt device=$(Agent.BuildDirectory)/results --opt o=bind results
          echo 'Hello world'
    - task: DockerCompose@0
      inputs:        
        dockerComposeFile: '**/docker-compose.yml'
        action: 'Run a Docker Compose command'
        dockerComposeCommand: 'up'
        arguments: '--abort-on-container-exit'